# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: 
date_format: "ordinal"
title:  二东的博客
subtitle: "充满勇气与力量，前行！前行！！"
description: "二东的个人博客"
keywords: SK, Shang Kai, kai.shang
favicon: /favicon.ico
timezone: Asia/Zhuhai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: kai.shang
organization: DingLi Inc.
organization_url: 
location: Zhuhai, China
email: aaron.shang@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 他山之石

  -
    href: /links/
    label: 专家链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: aaronshang/aaronshang.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: aaronshang
douban_username: aaronshang
facebook_username: aaronshang
weibo_username: aaronshang
zhihu_username: aaronshang
twitter_username: aaronshang

# ---------------- #
#      Comments    #

# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
# duoshuo_username: skwaityou
disqus_username: shangkai007-top

# 在使用 disqus 的时候可点击显示多说评论框
# lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [iOS, Android, Reverse Engineering]
